#!/bin/sh
# PekWM start file
# This file is a simple shell script; It gets run on pekwm startup, after 
# the theme and all config has loaded if it is set executable
# (chmod +x start).
#
# This is different from ~/.xinitrc because a normal configuration of 
# .xinitrc you'll run all commands, then launch the window manager last.
#
# It also gets re-run every time pekwm is restarted.
# 
# As for it's usefulness, well, it's up to you. I actually set my background
# from my start file; since it runs after the theme gets loaded, this 
# effectively overrides whatever's in the theme.
# 
# There's probably a few other good uses for it, too. I mainly pushed for it
# because when I was doing fluxbox's docs, people used to complain that there
# wasn't one, and I wanted to avoid that for pekwm. ;) --eyez

# Enable Eyecandy - off by default
xcompmgr -c -t-5 -l-5 -r4.2 -o.55 &

#(sleep 1s && aplay ~/.sounds/logon.wav) &

# pulseaudio --start &

# tilda &

# Set Wallpaper
# wallchange &
DISPLAY=:0.1 feh --bg-scale '/home/kittykatt/.wallpapers/watch_your_back_animeBabe.jpg'
DISPLAY=:0.0 feh --bg-scale '/home/kittykatt/.wallpapers/neiko.png'
# Enable Keyboard Bindings
xbindkeys &

sleep 1s

# Launch Panel
tint2start &
# Start thunar in daemon mode
#Thunar --daemon &

#sleep 1s

# SSHFS Server
# sshfs arch-server:/home/kittykatt ~/sshfs/archserver-home/
# sshfs arch-server:/srv/http ~/sshfs/archserver-served/
