#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
# exec xterm
# exec dbus-launch --exit-with-session openbox-session
# openbox-session
#export GTK_MODULES=$GTK_MODULES:screenhop
# exec pekwm &

#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#    for f in /etc/X11/xinit/xinitrc.d/*; do
#        [ -x "$f" ] && . "$f"
#    done
#    unset f
#fi

# Dbus
# if which dbus-launch >/dev/null 2>&1 && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
#        eval `dbus-launch --sh-syntax --exit-with-session`
# fi

# Policykit
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

#exec pekwm &
#exec pekwm --display :0.1
exec ck-launch-session dbus-launch pekwm  &
exec ck-launch-session dbus-launch pekwm --display :0.1

# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
